NUWCDIVNPT/stigman-watcher

lib/args.js
lib/cargo.js
lib/parse.js
package-lock.json
package.json

- Updated the CKL parser to map <STATUS>Not_Reviewed</STATUS> where <FINDING_DETAILS> is not empty as result informational. All other `Not_Reviewed` reviews will continue to be ignored.
- Added option `--strict-revision-check` whose default is `false`. This is a behavior change from previous Watcher releases. For CKL, unless this option is set the parser will attempt to POST reviews from checklists of uninstalled STIG revisions. The API will accept reviews for Rules that are associated with an installed STIG revision, and reject reviews for Rules not associated with an installed STIG revision.

Bump release to 1.1.1

---

package-lock.json
package.json

Resolves a [dependency vulnerability issue with strip-ansi -> ansi-regex](https://github.com/advisories/GHSA-93q8-gq69-wqmw) which was introduced in 4.1.7. The added feature is not required for this project.

chore: downgrade prompt-sync to v4.1.6

---

.gitignore
index.js
lib/ReviewParser.js
lib/api.js
lib/auth.js
lib/parse.js
package-lock.json
package.json

Resolves #20 
Resolves #18 
Resolves #11 
Resolves #10
- Minimum STIG Manager API version is updated from 1.1.0 => 1.2.7
- Adds support for the `resultEngine` property of Review 
- The serializers now attempt to fetch configuration options from `Collection.metadata.importOptions`. If this metadata property is absent, a default configuration object which mimics previous serialization behavior is used. Support for configuring custom options will be considered in future PRs. See the STIG Manager API definition for property descriptions.
```
const defaultImportOptions = {
autoStatus: 'saved',
unreviewed: 'commented',
unreviewedCommented: 'informational',
emptyDetail: 'replace',
emptyComment: 'ignore',
allowCustom: false
}
```
- The serializers now reference Collection field and status …

feat: update review parsing and serialization

---

lib/ReviewParser.js

Eval-STIG team settled on `<module><name>` instead of `<module><root>`

fix: eval-stig module name element

---

lib/ReviewParser.js
package-lock.json
package.json

CKL serializer was failing when parsing CKL with no root XML comment. Added the optional chaining operator.
Also bumped version to 1.2.6

fix: handle CKL with no root XML comment

---

lib/cargo.js

Resolves #40 
In `lib/cargo.js`, normalizes the cklWebDb* property values to lowercase when attempting to match an existing Asset.

fix: case insensitive matching

---

lib/ReviewParser.js

Create revision string only if STIG version and Release info supports it. Otherwise null.
Matches "Parsers.js" in the stig-manager repo.

Create revision string only if STIG version and Release info supports it.

---

lib/ReviewParser.js

This PR synchronizes XCCDF parsing code between the STIG Manager web app and Watcher. See [this STIG Manager pull request](https://github.com/NUWCDIVNPT/stig-manager/pull/931).
This code successfully processes the sanitized sample files from ACAS and HBSS which were provided with [here](https://github.com/NUWCDIVNPT/stig-manager/issues/890). We hope for additional feedback from the community to establish we can handle all of the real-world XCCDF from those tools.
This PR handles the non-standard value for `<TestResult test-system>` that is seen in the HBSS file. According to [the XCCDF specification](https://csrc.nist.gov/CSRC/media/Publications/nistir/7275/rev-4/final/documents/nistir-7275r4_updated-march-2012_clean.pdf) the `test-system` attribute "SHOULD be either a CPE name or a CPE …

feat: parse and import XCCDF with root-level TestResult

---

bin/.gitignore
build.sh
dist/.gitignore
pkg.config.json

A bash shell script that generates the binary artifacts provided with our Releases. Generates a Windows EXE and a Linux static binary.

feat: build script for executables

---

lib/ReviewParser.js
lib/parse.js
lib/scan.js

Resolves: #59 
Update ReviewParser.js from the existing STIG Manager web app

feat: parse cklb

---

lib/cargo.js

Resolves: #55
Problem: WATCHER_CARGO_SIZE=1 would result in an error due to not being able to iterate over this.parsedResults. 
Solution: If this.parsedResults is an object wrap it in an array.

WATCHER_CARGO_SIZE=1 Error

---

lib/cargo.js
package-lock.json
package.json

TaskObject was being instantiated without the necessary `options` property. Fixed and incremented the version to 1.4.1

hotfix: call TaskObject with an option property; bump to 1.4.1

---

.gitignore
build.sh
index.js
lib/api.js
lib/args.js
lib/auth.js
lib/cargo.js
lib/events.js
lib/help.js
lib/logger.js
lib/parse.js
lib/scan.js
package-lock.json
package.json
pkg.config.json

resolves: #85 
The following PR will migrate Stigman-Watcher to use ESM style modules.
Other than the syntactical changes to migrate to ESM, the only logic that needed to be refactored is in args.js to:
Obtain the watcher version number from package,json
Logic behind exiting the application when validating the client secret or key.
This PR also addressed simple sonar cloud findings.

Re: Migrate from CommonJS to ESM

---

lib/parse.js
package-lock.json
package.json

This PR adds support for the `sourceRef` property which was recently added to the options object accepted by the parse functions in `stig-manager-client-modules`
- passes the current filename to the parse functions as the option `sourceRef`
- removes the post-parse assignment to `parseResult.file`
- updates `package.json` to pull `stig-manager-client-modules` from the HEAD of https://github.com/NUWCDIVNPT/stig-manager-client-modules
- updates `package-lock.json` with the current versions of dependencies

feat: pass filename to parsers as sourceRef 

---

lib/cargo.js
lib/parse.js
package-lock.json
package.json

- install  `@nuwcdivnpt/stig-manager-client-modules` from npm instead of from GitHub
- remove `fast-xml-parser` and `he` since their capabilities are now implemented by `@nuwcdivnpt/stig-manager-client-modules`
- remove deprecated `XMLParser` and `valueProcessor` options from the call to the parse function
- update all dependencies in `package-lock.json`

chore: remove/update dependencies

---

lib/events.js

This fix introduces the ability to process CKLB files when running watcher in event mode.

Hot fix: Adds ability to process cklb files when in event mode. 

---

.github/workflows/build-binary-artifacts.yml
.github/workflows/sonarcloud.yml
.github/workflows/unit-testing.yml

This pull request upgrades the Node.js version for actions within this repository to use Node.js 20. Additionally, it modifies the workflow by incorporating unit-testing.yml into the 'on:' trigger, ensuring the workflow initiates whenever there are updates to it.
The following actions were changed to version 4:
actions/checkout
actions/upload-artifact
actions/setup-node

Chore: Update github actions to v4

---

lib/args.js

Resolves #110 
Sets the `version` variable from a static string instead of trying to read it from package.json. This is a hotfix until, or if, we figure out an approach for reading the version string from package.json in the snapshot filesystem of the binaries.

fix: static version string in args.js

---

lib/auth.js

This PR fixes the method that performs client secret authentication so the token request includes the `scope` parameter.

fix: send scopes with client secret authentication

---

.gitignore
build.sh
lib/args.js
pkg.config.json

- Revert the static assignment to the `version` variable introduced by #111 and once again call `getVersion()` to read it from `package.json`.
- Update `getVersion()` to return a value from the catch handler so errors here do not crash the entire process. Returning `undefined` from `getVersion()`  was the ultimate cause of #110.
- Construct the path to `package.json` using `process.pkg.defaultEntrypoint` if it exists, in order to support the binary build system.
The build system was updated to:
- include `package.json` in the binary snapshot file system
- change the extension of the CommonJS bundled code to `.cjs` so it is processed as CommonJS when in the snapshot filesystem. Our `package.json` includes `{"type": "module"}`, so using the previous name `bundle.js` caused node to attempt …

fix: read from package.json and include it in binary snapshot fs

---

lib/api.js
lib/args.js
lib/auth.js
lib/consts.js

Resolves: #120
This PR enhances our API request timeout to be configurable. It Also increases the default request timeout to 20 seconds.

Enhancement: response timeout to be configurable from environment

---

index.js
lib/api.js
lib/args.js
lib/auth.js
lib/cargo.js
lib/consts.js

Resolves #124
Resolves #118 
This PR refactors `cargo.js` and `api.js` to support more efficient fetches of Assets from the STIG Manager API. Instead of each batch fetching all the Assets for the target Collection, each batch will fetch only those Assets which are targets of the batch's parsed results.
In addition, the error handling for `apiRequest()` was refactrored to align with the real-world behavior of the API, which returns 422 upon duplicate name collisions and 503 when the service is unavailable.

feat: concurrent asset fetches

---

lib/scan.js

Resolves #117 
Alternative approach to #127 that:
- schedules the next scan with a delay relative to the last worker of the current processing pipeline.
- avoids non-productive invocations of `startScanner()` by only scheduling when workers are finished

feat: schedule scan based on queue events

---

lib/api.js
lib/args.js
lib/cargo.js
lib/events.js
lib/parse.js
lib/scan.js
package-lock.json
package.json

Resolves #121 
Resolves #119
- moves alarm handlers that pause the queues from `scan.js` and `event.js` into `parse.js` and `cargo.js`.
- refactors error handling in `api.js`
- updates many object literals to use shorthand property notation
- updates `@nuwcdivnpt/stig-manager-client-modules` to v1.4.2, which adds support for truncating Asset properties in accordance with the STIG Manager API definition
- updates all other dependencies to their most recent versions, in accordance with their semver rules in `package.json`

refactor: alarm handling

---

lib/auth.js
package-lock.json
package.json

resolves: #135 
resolves: #134 
The client credentials flow is an oauth flow, not an oidc flow, so requesting "openid" is inappropriate. Some authorization services(ie. okta) will not provide a token if this scope is requested.
If for some reason it is required by another service, Watcher already allows extra scopes to be specified.

fix: Remove hard-coded "openid" scope from token request; dependency updates

---

lib/api.js
lib/parse.js

changes from accessLevel to roleId to match stig-manager API.

feat: change accessLevel to RoleId 

---

package-lock.json
package.json

Changes accessLevel to RoleId to support changes in stigman api 1.5.3. Backwards compatible with older versions of the API.

chore: release 1.5.1. Updates to support stigman api changes in 1.5.3

---

lib/api.js
lib/cargo.js
package-lock.json
package.json

resolves part of [this issue ](https://github.com/orgs/NUWCDIVNPT/projects/3/views/8?pane=issue&itemId=112999150&issue=NUWCDIVNPT%7Cstig-manager-client-modules%7C43)
resolves #154 
This pull request refactors the `getCollectionAssets` function in `lib/api.js` to construct the 'effective name' of an asset with ckl metadata. This was needed because it is possible to have assets in the api with different names but equal ckl metadata values. 
* [`lib/api.js`](diffhunk://#diff-3814d8caba69e5fdf3b23eed56ec7d708b8ede5aed6d686ac579421877938ec7L152-R176): Replaced separate named and metadata endpoint arrays with a unified `nameBasedEndpoints` array. The logic now uses a helper function, `createEffectiveName`, to generate effective names for targets with `ckl` metadata.
* …

Asset name issue 
